version: '3.5'

services:
  magicmirror:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magicmirror
    image: docker-magicmirror:latest
    ports:
      - 8080:8080
    volumes:
      - ./config:/opt/magic_mirror/config
      - ./modules:/opt/magic_mirror/modules
    environment:
      - TZ=Europe/Zurich
    restart: unless-stopped
